CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
MIDI_ENABLE = no            # MIDI controls
AUDIO_ENABLE = no       
MOUSEKEY_ENABLE = no  # Mouse keys
RGBLIGHT_ENABLE = yes
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
BOOTMAGIC_ENABLE = no
WPM_ENABLE = yes